# iso3166_1_alpha_2.py
# Complete list of ISO 3166-1 alpha-2 country codes with number (starting from 002) and name
iso3166_alpha2 = {
    "AF": {"number": "002", "name": "Afghanistan"},
    "AL": {"number": "003", "name": "Albania"},
    "DZ": {"number": "004", "name": "Algeria"},
    "AS": {"number": "005", "name": "American Samoa"},
    "AD": {"number": "006", "name": "Andorra"},
    "AO": {"number": "007", "name": "Angola"},
    "AI": {"number": "008", "name": "Anguilla"},
    "AQ": {"number": "009", "name": "Antarctica"},
    "AG": {"number": "010", "name": "Antigua and Barbuda"},
    "AR": {"number": "011", "name": "Argentina"},
    "AM": {"number": "012", "name": "Armenia"},
    "AW": {"number": "013", "name": "Aruba"},
    "AU": {"number": "014", "name": "Australia"},
    "AT": {"number": "015", "name": "Austria"},
    "AZ": {"number": "016", "name": "Azerbaijan"},
    "BS": {"number": "017", "name": "Bahamas"},
    "BH": {"number": "018", "name": "Bahrain"},
    "BD": {"number": "019", "name": "Bangladesh"},
    "BB": {"number": "020", "name": "Barbados"},
    "BY": {"number": "021", "name": "Belarus"},
    "BE": {"number": "022", "name": "Belgium"},
    "BZ": {"number": "023", "name": "Belize"},
    "BJ": {"number": "024", "name": "Benin"},
    "BM": {"number": "025", "name": "Bermuda"},
    "BT": {"number": "026", "name": "Bhutan"},
    "BO": {"number": "027", "name": "Bolivia"},
    "BA": {"number": "028", "name": "Bosnia and Herzegovina"},
    "BW": {"number": "029", "name": "Botswana"},
    "BR": {"number": "030", "name": "Brazil"},
    "IO": {"number": "031", "name": "British Indian Ocean Territory"},
    "VG": {"number": "032", "name": "British Virgin Islands"},
    "BN": {"number": "033", "name": "Brunei"},
    "BG": {"number": "034", "name": "Bulgaria"},
    "BF": {"number": "035", "name": "Burkina Faso"},
    "BI": {"number": "036", "name": "Burundi"},
    "KH": {"number": "037", "name": "Cambodia"},
    "CM": {"number": "038", "name": "Cameroon"},
    "CA": {"number": "039", "name": "Canada"},
    "CV": {"number": "040", "name": "Cape Verde"},
    "KY": {"number": "041", "name": "Cayman Islands"},
    "CF": {"number": "042", "name": "Central African Republic"},
    "TD": {"number": "043", "name": "Chad"},
    "CL": {"number": "044", "name": "Chile"},
    "CN": {"number": "045", "name": "China"},
    "CX": {"number": "046", "name": "Christmas Island"},
    "CC": {"number": "047", "name": "Cocos (Keeling) Islands"},
    "CO": {"number": "048", "name": "Colombia"},
    "KM": {"number": "049", "name": "Comoros"},
    "CG": {"number": "050", "name": "Congo"},
    "CD": {"number": "051", "name": "Congo (Democratic Republic)"},
    "CK": {"number": "052", "name": "Cook Islands"},
    "CR": {"number": "053", "name": "Costa Rica"},
    "HR": {"number": "054", "name": "Croatia"},
    "CU": {"number": "055", "name": "Cuba"},
    "CW": {"number": "056", "name": "Curaçao"},
    "CY": {"number": "057", "name": "Cyprus"},
    "CZ": {"number": "058", "name": "Czech Republic"},
    "DK": {"number": "059", "name": "Denmark"},
    "DJ": {"number": "060", "name": "Djibouti"},
    "DM": {"number": "061", "name": "Dominica"},
    "DO": {"number": "062", "name": "Dominican Republic"},
    "EC": {"number": "063", "name": "Ecuador"},
    "EG": {"number": "064", "name": "Egypt"},
    "SV": {"number": "065", "name": "El Salvador"},
    "GQ": {"number": "066", "name": "Equatorial Guinea"},
    "ER": {"number": "067", "name": "Eritrea"},
    "EE": {"number": "068", "name": "Estonia"},
    "ET": {"number": "069", "name": "Ethiopia"},
    "FK": {"number": "070", "name": "Falkland Islands"},
    "FO": {"number": "071", "name": "Faroe Islands"},
    "FJ": {"number": "072", "name": "Fiji"},
    "FI": {"number": "073", "name": "Finland"},
    "FR": {"number": "074", "name": "France"},
    "GF": {"number": "075", "name": "French Guiana"},
    "PF": {"number": "076", "name": "French Polynesia"},
    "TF": {"number": "077", "name": "French Southern Territories"},
    "GA": {"number": "078", "name": "Gabon"},
    "GM": {"number": "079", "name": "Gambia"},
    "GE": {"number": "080", "name": "Georgia"},
    "DE": {"number": "081", "name": "Germany"},
    "GH": {"number": "082", "name": "Ghana"},
    "GI": {"number": "083", "name": "Gibraltar"},
    "GR": {"number": "084", "name": "Greece"},
    "GL": {"number": "085", "name": "Greenland"},
    "GD": {"number": "086", "name": "Grenada"},
    "GP": {"number": "087", "name": "Guadeloupe"},
    "GU": {"number": "088", "name": "Guam"},
    "GT": {"number": "089", "name": "Guatemala"},
    "GG": {"number": "090", "name": "Guernsey"},
    "GN": {"number": "091", "name": "Guinea"},
    "GW": {"number": "092", "name": "Guinea-Bissau"},
    "GY": {"number": "093", "name": "Guyana"},
    "HT": {"number": "094", "name": "Haiti"},
    "HN": {"number": "095", "name": "Honduras"},
    "HK": {"number": "096", "name": "Hong Kong"},
    "HU": {"number": "097", "name": "Hungary"},
    "IS": {"number": "098", "name": "Iceland"},
    "IN": {"number": "099", "name": "India"},
    "ID": {"number": "100", "name": "Indonesia"},
    "IR": {"number": "101", "name": "Iran"},
    "IQ": {"number": "102", "name": "Iraq"},
    "IE": {"number": "103", "name": "Ireland"},
    "IM": {"number": "104", "name": "Isle of Man"},
    "IL": {"number": "105", "name": "Israel"},
    "IT": {"number": "106", "name": "Italy"},
    "CI": {"number": "107", "name": "Ivory Coast"},
    "JM": {"number": "108", "name": "Jamaica"},
    "JP": {"number": "109", "name": "Japan"},
    "JE": {"number": "110", "name": "Jersey"},
    "JO": {"number": "111", "name": "Jordan"},
    "KZ": {"number": "112", "name": "Kazakhstan"},
    "KE": {"number": "113", "name": "Kenya"},
    "KI": {"number": "114", "name": "Kiribati"},
    "KP": {"number": "115", "name": "North Korea"},
    "KR": {"number": "116", "name": "South Korea"},
    "KW": {"number": "117", "name": "Kuwait"},
    "KG": {"number": "118", "name": "Kyrgyzstan"},
    "LA": {"number": "119", "name": "Laos"},
    "LV": {"number": "120", "name": "Latvia"},
    "LB": {"number": "121", "name": "Lebanon"},
    "LS": {"number": "122", "name": "Lesotho"},
    "LR": {"number": "123", "name": "Liberia"},
    "LY": {"number": "124", "name": "Libya"},
    "LI": {"number": "125", "name": "Liechtenstein"},
    "LT": {"number": "126", "name": "Lithuania"},
    "LU": {"number": "127", "name": "Luxembourg"},
    "MO": {"number": "128", "name": "Macao"},
    "MK": {"number": "129", "name": "North Macedonia"},
    "MG": {"number": "130", "name": "Madagascar"},
    "MW": {"number": "131", "name": "Malawi"},
    "MY": {"number": "132", "name": "Malaysia"},
    "MV": {"number": "133", "name": "Maldives"},
    "ML": {"number": "134", "name": "Mali"},
    "MT": {"number": "135", "name": "Malta"},
    "MH": {"number": "136", "name": "Marshall Islands"},
    "MQ": {"number": "137", "name": "Martinique"},
    "MR": {"number": "138", "name": "Mauritania"},
    "MU": {"number": "139", "name": "Mauritius"},
    "YT": {"number": "140", "name": "Mayotte"},
    "MX": {"number": "141", "name": "Mexico"},
    "FM": {"number": "142", "name": "Micronesia"},
    "MD": {"number": "143", "name": "Moldova"},
    "MC": {"number": "144", "name": "Monaco"},
    "MN": {"number": "145", "name": "Mongolia"},
    "ME": {"number": "146", "name": "Montenegro"},
    "MS": {"number": "147", "name": "Montserrat"},
    "MA": {"number": "148", "name": "Morocco"},
    "MZ": {"number": "149", "name": "Mozambique"},
    "MM": {"number": "150", "name": "Myanmar"},
    "NA": {"number": "151", "name": "Namibia"},
    "NR": {"number": "152", "name": "Nauru"},
    "NP": {"number": "153", "name": "Nepal"},
    "NL": {"number": "154", "name": "Netherlands"},
    "NC": {"number": "155", "name": "New Caledonia"},
    "NZ": {"number": "156", "name": "New Zealand"},
    "NI": {"number": "157", "name": "Nicaragua"},
    "NE": {"number": "158", "name": "Niger"},
    "NG": {"number": "159", "name": "Nigeria"},
    "NU": {"number": "160", "name": "Niue"},
    "NF": {"number": "161", "name": "Norfolk Island"},
    "MP": {"number": "162", "name": "Northern Mariana Islands"},
    "NO": {"number": "163", "name": "Norway"},
    "OM": {"number": "164", "name": "Oman"},
    "PK": {"number": "165", "name": "Pakistan"},
    "PW": {"number": "166", "name": "Palau"},
    "PS": {"number": "167", "name": "Palestine"},
    "PA": {"number": "168", "name": "Panama"},
    "PG": {"number": "169", "name": "Papua New Guinea"},
    "PY": {"number": "170", "name": "Paraguay"},
    "PE": {"number": "171", "name": "Peru"},
    "PH": {"number": "172", "name": "Philippines"},
    "PN": {"number": "173", "name": "Pitcairn"},
    "PL": {"number": "174", "name": "Poland"},
    "PT": {"number": "175", "name": "Portugal"},
    "PR": {"number": "176", "name": "Puerto Rico"},
    "QA": {"number": "177", "name": "Qatar"},
    "RE": {"number": "178", "name": "Réunion"},
    "RO": {"number": "179", "name": "Romania"},
    "RU": {"number": "180", "name": "Russia"},
    "RW": {"number": "181", "name": "Rwanda"},
    "BL": {"number": "182", "name": "Saint Barthélemy"},
    "SH": {"number": "183", "name": "Saint Helena"},
    "KN": {"number": "184", "name": "Saint Kitts and Nevis"},
    "LC": {"number": "185", "name": "Saint Lucia"},
    "MF": {"number": "186", "name": "Saint Martin"},
    "PM": {"number": "187", "name": "Saint Pierre and Miquelon"},
    "VC": {"number": "188", "name": "Saint Vincent and the Grenadines"},
    "WS": {"number": "189", "name": "Samoa"},
    "SM": {"number": "190", "name": "San Marino"},
    "ST": {"number": "191", "name": "São Tomé and Príncipe"},
    "SA": {"number": "192", "name": "Saudi Arabia"},
    "SN": {"number": "193", "name": "Senegal"},
    "RS": {"number": "194", "name": "Serbia"},
    "SC": {"number": "195", "name": "Seychelles"},
    "SL": {"number": "196", "name": "Sierra Leone"},
    "SG": {"number": "197", "name": "Singapore"},
    "SX": {"number": "198", "name": "Sint Maarten"},
    "SK": {"number": "199", "name": "Slovakia"},
    "SI": {"number": "200", "name": "Slovenia"},
    "SB": {"number": "201", "name": "Solomon Islands"},
    "SO": {"number": "202", "name": "Somalia"},
    "ZA": {"number": "203", "name": "South Africa"},
    "GS": {"number": "204", "name": "South Georgia"},
    "SS": {"number": "205", "name": "South Sudan"},
    "ES": {"number": "206", "name": "Spain"},
    "LK": {"number": "207", "name": "Sri Lanka"},
    "SD": {"number": "208", "name": "Sudan"},
    "SR": {"number": "209", "name": "Suriname"},
    "SJ": {"number": "210", "name": "Svalbard and Jan Mayen"},
    "SZ": {"number": "211", "name": "Eswatini"},
    "SE": {"number": "212", "name": "Sweden"},
    "CH": {"number": "213", "name": "Switzerland"},
    "SY": {"number": "214", "name": "Syria"},
    "TW": {"number": "215", "name": "Taiwan"},
    "TJ": {"number": "216", "name": "Tajikistan"},
    "TZ": {"number": "217", "name": "Tanzania"},
    "TH": {"number": "218", "name": "Thailand"},
    "TL": {"number": "219", "name": "Timor-Leste"},
    "TG": {"number": "220", "name": "Togo"},
    "TK": {"number": "221", "name": "Tokelau"},
    "TO": {"number": "222", "name": "Tonga"},
    "TT": {"number": "223", "name": "Trinidad and Tobago"},
    "TN": {"number": "224", "name": "Tunisia"},
    "TR": {"number": "225", "name": "Turkey"},
    "TM": {"number": "226", "name": "Turkmenistan"},
    "TC": {"number": "227", "name": "Turks and Caicos Islands"},
    "TV": {"number": "228", "name": "Tuvalu"},
    "UG": {"number": "229", "name": "Uganda"},
    "UA": {"number": "230", "name": "Ukraine"},
    "AE": {"number": "231", "name": "United Arab Emirates"},
    "GB": {"number": "232", "name": "United Kingdom"},
    "US": {"number": "233", "name": "United States"},
    "UM": {"number": "234", "name": "United States Minor Outlying Islands"},
    "UY": {"number": "235", "name": "Uruguay"},
    "UZ": {"number": "236", "name": "Uzbekistan"},
    "VU": {"number": "237", "name": "Vanuatu"},
    "VE": {"number": "238", "name": "Venezuela"},
    "VN": {"number": "239", "name": "Vietnam"},
    "VI": {"number": "240", "name": "Virgin Islands (U.S.)"},
    "WF": {"number": "241", "name": "Wallis and Futuna"},
    "EH": {"number": "242", "name": "Western Sahara"},
    "YE": {"number": "243", "name": "Yemen"},
    "ZM": {"number": "244", "name": "Zambia"},
    "ZW": {"number": "245", "name": "Zimbabwe"},
    "AX": {"number": "246", "name": "Åland Islands"},
    "BQ": {"number": "247", "name": "Bonaire, Sint Eustatius and Saba"},
    "SS": {"number": "248", "name": "South Sudan"},
    "XK": {"number": "249", "name": "Kosovo"}
}