// iso3166-1-alpha-2.js
// Complete list of ISO 3166-1 alpha-2 country codes, numbered starting from 002
const iso3166Alpha2 = {
  "002": { code: "AF", name: "Afghanistan" },
  "003": { code: "AL", name: "Albania" },
  "004": { code: "DZ", name: "Algeria" },
  "005": { code: "AS", name: "American Samoa" },
  "006": { code: "AD", name: "Andorra" },
  "007": { code: "AO", name: "Angola" },
  "008": { code: "AI", name: "Anguilla" },
  "009": { code: "AQ", name: "Antarctica" },
  "010": { code: "AG", name: "Antigua and Barbuda" },
  "011": { code: "AR", name: "Argentina" },
  "012": { code: "AM", name: "Armenia" },
  "013": { code: "AW", name: "Aruba" },
  "014": { code: "AU", name: "Australia" },
  "015": { code: "AT", name: "Austria" },
  "016": { code: "AZ", name: "Azerbaijan" },
  "017": { code: "BS", name: "Bahamas" },
  "018": { code: "BH", name: "Bahrain" },
  "019": { code: "BD", name: "Bangladesh" },
  "020": { code: "BB", name: "Barbados" },
  "021": { code: "BY", name: "Belarus" },
  "022": { code: "BE", name: "Belgium" },
  "023": { code: "BZ", name: "Belize" },
  "024": { code: "BJ", name: "Benin" },
  "025": { code: "BM", name: "Bermuda" },
  "026": { code: "BT", name: "Bhutan" },
  "027": { code: "BO", name: "Bolivia" },
  "028": { code: "BA", name: "Bosnia and Herzegovina" },
  "029": { code: "BW", name: "Botswana" },
  "030": { code: "BR", name: "Brazil" },
  "031": { code: "IO", name: "British Indian Ocean Territory" },
  "032": { code: "VG", name: "British Virgin Islands" },
  "033": { code: "BN", name: "Brunei" },
  "034": { code: "BG", name: "Bulgaria" },
  "035": { code: "BF", name: "Burkina Faso" },
  "036": { code: "BI", name: "Burundi" },
  "037": { code: "KH", name: "Cambodia" },
  "038": { code: "CM", name: "Cameroon" },
  "039": { code: "CA", name: "Canada" },
  "040": { code: "CV", name: "Cape Verde" },
  "041": { code: "KY", name: "Cayman Islands" },
  "042": { code: "CF", name: "Central African Republic" },
  "043": { code: "TD", name: "Chad" },
  "044": { code: "CL", name: "Chile" },
  "045": { code: "CN", name: "China" },
  "046": { code: "CX", name: "Christmas Island" },
  "047": { code: "CC", name: "Cocos (Keeling) Islands" },
  "048": { code: "CO", name: "Colombia" },
  "049": { code: "KM", name: "Comoros" },
  "050": { code: "CG", name: "Congo" },
  "051": { code: "CD", name: "Congo (Democratic Republic)" },
  "052": { code: "CK", name: "Cook Islands" },
  "053": { code: "CR", name: "Costa Rica" },
  "054": { code: "HR", name: "Croatia" },
  "055": { code: "CU", name: "Cuba" },
  "056": { code: "CW", name: "Curaçao" },
  "057": { code: "CY", name: "Cyprus" },
  "058": { code: "CZ", name: "Czech Republic" },
  "059": { code: "DK", name: "Denmark" },
  "060": { code: "DJ", name: "Djibouti" },
  "061": { code: "DM", name: "Dominica" },
  "062": { code: "DO", name: "Dominican Republic" },
  "063": { code: "EC", name: "Ecuador" },
  "064": { code: "EG", name: "Egypt" },
  "065": { code: "SV", name: "El Salvador" },
  "066": { code: "GQ", name: "Equatorial Guinea" },
  "067": { code: "ER", name: "Eritrea" },
  "068": { code: "EE", name: "Estonia" },
  "069": { code: "ET", name: "Ethiopia" },
  "070": { code: "FK", name: "Falkland Islands" },
  "071": { code: "FO", name: "Faroe Islands" },
  "072": { code: "FJ", name: "Fiji" },
  "073": { code: "FI", name: "Finland" },
  "074": { code: "FR", name: "France" },
  "075": { code: "GF", name: "French Guiana" },
  "076": { code: "PF", name: "French Polynesia" },
  "077": { code: "TF", name: "French Southern Territories" },
  "078": { code: "GA", name: "Gabon" },
  "079": { code: "GM", name: "Gambia" },
  "080": { code: "GE", name: "Georgia" },
  "081": { code: "DE", name: "Germany" },
  "082": { code: "GH", name: "Ghana" },
  "083": { code: "GI", name: "Gibraltar" },
  "084": { code: "GR", name: "Greece" },
  "085": { code: "GL", name: "Greenland" },
  "086": { code: "GD", name: "Grenada" },
  "087": { code: "GP", name: "Guadeloupe" },
  "088": { code: "GU", name: "Guam" },
  "089": { code: "GT", name: "Guatemala" },
  "090": { code: "GG", name: "Guernsey" },
  "091": { code: "GN", name: "Guinea" },
  "092": { code: "GW", name: "Guinea-Bissau" },
  "093": { code: "GY", name: "Guyana" },
  "094": { code: "HT", name: "Haiti" },
  "095": { code: "HN", name: "Honduras" },
  "096": { code: "HK", name: "Hong Kong" },
  "097": { code: "HU", name: "Hungary" },
  "098": { code: "IS", name: "Iceland" },
  "099": { code: "IN", name: "India" },
  "100": { code: "ID", name: "Indonesia" },
  "101": { code: "IR", name: "Iran" },
  "102": { code: "IQ", name: "Iraq" },
  "103": { code: "IE", name: "Ireland" },
  "104": { code: "IM", name: "Isle of Man" },
  "105": { code: "IL", name: "Israel" },
  "106": { code: "IT", name: "Italy" },
  "107": { code: "CI", name: "Ivory Coast" },
  "108": { code: "JM", name: "Jamaica" },
  "109": { code: "JP", name: "Japan" },
  "110": { code: "JE", name: "Jersey" },
  "111": { code: "JO", name: "Jordan" },
  "112": { code: "KZ", name: "Kazakhstan" },
  "113": { code: "KE", name: "Kenya" },
  "114": { code: "KI", name: "Kiribati" },
  "115": { code: "KP", name: "North Korea" },
  "116": { code: "KR", name: "South Korea" },
  "117": { code: "KW", name: "Kuwait" },
  "118": { code: "KG", name: "Kyrgyzstan" },
  "119": { code: "LA", name: "Laos" },
  "120": { code: "LV", name: "Latvia" },
  "121": { code: "LB", name: "Lebanon" },
  "122": { code: "LS", name: "Lesotho" },
  "123": { code: "LR", name: "Liberia" },
  "124": { code: "LY", name: "Libya" },
  "125": { code: "LI", name: "Liechtenstein" },
  "126": { code: "LT", name: "Lithuania" },
  "127": { code: "LU", name: "Luxembourg" },
  "128": { code: "MO", name: "Macao" },
  "129": { code: "MK", name: "North Macedonia" },
  "130": { code: "MG", name: "Madagascar" },
  "131": { code: "MW", name: "Malawi" },
  "132": { code: "MY", name: "Malaysia" },
  "133": { code: "MV", name: "Maldives" },
  "134": { code: "ML", name: "Mali" },
  "135": { code: "MT", name: "Malta" },
  "136": { code: "MH", name: "Marshall Islands" },
  "137": { code: "MQ", name: "Martinique" },
  "138": { code: "MR", name: "Mauritania" },
  "139": { code: "MU", name: "Mauritius" },
  "140": { code: "YT", name: "Mayotte" },
  "141": { code: "MX", name: "Mexico" },
  "142": { code: "FM", name: "Micronesia" },
  "143": { code: "MD", name: "Moldova" },
  "144": { code: "MC", name: "Monaco" },
  "145": { code: "MN", name: "Mongolia" },
  "146": { code: "ME", name: "Montenegro" },
  "147": { code: "MS", name: "Montserrat" },
  "148": { code: "MA", name: "Morocco" },
  "149": { code: "MZ", name: "Mozambique" },
  "150": { code: "MM", name: "Myanmar" },
  "151": { code: "NA", name: "Namibia" },
  "152": { code: "NR", name: "Nauru" },
  "153": { code: "NP", name: "Nepal" },
  "154": { code: "NL", name: "Netherlands" },
  "155": { code: "NC", name: "New Caledonia" },
  "156": { code: "NZ", name: "New Zealand" },
  "157": { code: "NI", name: "Nicaragua" },
  "158": { code: "NE", name: "Niger" },
  "159": { code: "NG", name: "Nigeria" },
  "160": { code: "NU", name: "Niue" },
  "161": { code: "NF", name: "Norfolk Island" },
  "162": { code: "MP", name: "Northern Mariana Islands" },
  "163": { code: "NO", name: "Norway" },
  "164": { code: "OM", name: "Oman" },
  "165": { code: "PK", name: "Pakistan" },
  "166": { code: "PW", name: "Palau" },
  "167": { code: "PS", name: "Palestine" },
  "168": { code: "PA", name: "Panama" },
  "169": { code: "PG", name: "Papua New Guinea" },
  "170": { code: "PY", name: "Paraguay" },
  "171": { code: "PE", name: "Peru" },
  "172": { code: "PH", name: "Philippines" },
  "173": { code: "PN", name: "Pitcairn" },
  "174": { code: "PL", name: "Poland" },
  "175": { code: "PT", name: "Portugal" },
  "176": { code: "PR", name: "Puerto Rico" },
  "177": { code: "QA", name: "Qatar" },
  "178": { code: "RE", name: "Réunion" },
  "179": { code: "RO", name: "Romania" },
  "180": { code: "RU", name: "Russia" },
  "181": { code: "RW", name: "Rwanda" },
  "182": { code: "BL", name: "Saint Barthélemy" },
  "183": { code: "SH", name: "Saint Helena" },
  "184": { code: "KN", name: "Saint Kitts and Nevis" },
  "185": { code: "LC", name: "Saint Lucia" },
  "186": { code: "MF", name: "Saint Martin" },
  "187": { code: "PM", name: "Saint Pierre and Miquelon" },
  "188": { code: "VC", name: "Saint Vincent and the Grenadines" },
  "189": { code: "WS", name: "Samoa" },
  "190": { code: "SM", name: "San Marino" },
  "191": { code: "ST", name: "São Tomé and Príncipe" },
  "192": { code: "SA", name: "Saudi Arabia" },
  "193": { code: "SN", name: "Senegal" },
  "194": { code: "RS", name: "Serbia" },
  "195": { code: "SC", name: "Seychelles" },
  "196": { code: "SL", name: "Sierra Leone" },
  "197": { code: "SG", name: "Singapore" },
  "198": { code: "SX", name: "Sint Maarten" },
  "199": { code: "SK", name: "Slovakia" },
  "200": { code: "SI", name: "Slovenia" },
  "201": { code: "SB", name: "Solomon Islands" },
  "202": { code: "SO", name: "Somalia" },
  "203": { code: "ZA", name: "South Africa" },
  "204": { code: "GS", name: "South Georgia" },
  "205": { code: "SS", name: "South Sudan" },
  "206": { code: "ES", name: "Spain" },
  "207": { code: "LK", name: "Sri Lanka" },
  "208": { code: "SD", name: "Sudan" },
  "209": { code: "SR", name: "Suriname" },
  "210": { code: "SJ", name: "Svalbard and Jan Mayen" },
  "211": { code: "SZ", name: "Eswatini" },
  "212": { code: "SE", name: "Sweden" },
  "213": { code: "CH", name: "Switzerland" },
  "214": { code: "SY", name: "Syria" },
  "215": { code: "TW", name: "Taiwan" },
  "216": { code: "TJ", name: "Tajikistan" },
  "217": { code: "TZ", name: "Tanzania" },
  "218": { code: "TH", name: "Thailand" },
  "219": { code: "TL", name: "Timor-Leste" },
  "220": { code: "TG", name: "Togo" },
  "221": { code: "TK", name: "Tokelau" },
  "222": { code: "TO", name: "Tonga" },
  "223": { code: "TT", name: "Trinidad and Tobago" },
  "224": { code: "TN", name: "Tunisia" },
  "225": { code: "TR", name: "Turkey" },
  "226": { code: "TM", name: "Turkmenistan" },
  "227": { code: "TC", name: "Turks and Caicos Islands" },
  "228": { code: "TV", name: "Tuvalu" },
  "229": { code: "UG", name: "Uganda" },
  "230": { code: "UA", name: "Ukraine" },
  "231": { code: "AE", name: "United Arab Emirates" },
  "232": { code: "GB", name: "United Kingdom" },
  "233": { code: "US", name: "United States" },
  "234": { code: "UM", name: "United States Minor Outlying Islands" },
  "235": { code: "UY", name: "Uruguay" },
  "236": { code: "UZ", name: "Uzbekistan" },
  "237": { code: "VU", name: "Vanuatu" },
  "238": { code: "VE", name: "Venezuela" },
  "239": { code: "VN", name: "Vietnam" },
  "240": { code: "VI", name: "Virgin Islands (U.S.)" },
  "241": { code: "WF", name: "Wallis and Futuna" },
  "242": { code: "EH", name: "Western Sahara" },
  "243": { code: "YE", name: "Yemen" },
  "244": { code: "ZM", name: "Zambia" },
  "245": { code: "ZW", name: "Zimbabwe" },
  "246": { code: "AX", name: "Åland Islands" },
  "247": { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  "248": { code: "SS", name: "South Sudan" },
  "249": { code: "XK", name: "Kosovo" }
};

module.exports = iso3166Alpha2;