UPDATE Grants SET recipient_ein = '002' WHERE colocator = 'FA:AF';
UPDATE Grants SET recipient_ein = '003' WHERE colocator = 'FA:AL';
UPDATE Grants SET recipient_ein = '004' WHERE colocator = 'FA:DZ' OR colocator = 'FA:AG' OR colocator = 'FA:AG';
UPDATE Grants SET recipient_ein = '010' WHERE colocator = 'FA:AG' OR colocator = 'FA:AC' OR colocator = 'FA:AC';
UPDATE Grants SET recipient_ein = '005' WHERE colocator = 'FA:AS';
UPDATE Grants SET recipient_ein = '006' WHERE colocator = 'FA:AD' OR colocator = 'FA:AN' OR colocator = 'FA:AN';
UPDATE Grants SET recipient_ein = '006' WHERE colocator = 'FA:AN';
UPDATE Grants SET recipient_ein = '007' WHERE colocator = 'FA:AO' OR colocator = 'FA:AV' OR colocator = 'FA:AV';
UPDATE Grants SET recipient_ein = '008' WHERE colocator = 'FA:AI';
UPDATE Grants SET recipient_ein = '009' WHERE colocator = 'FA:AQ' OR colocator = 'FA:AY' OR colocator = 'FA:AY';
UPDATE Grants SET recipient_ein = '009' WHERE colocator = 'FA:AY';
UPDATE Grants SET recipient_ein = '011' WHERE colocator = 'FA:AR';
UPDATE Grants SET recipient_ein = '012' WHERE colocator = 'FA:AM';
UPDATE Grants SET recipient_ein = '013' WHERE colocator = 'FA:AW' OR colocator = 'FA:AA' OR colocator = 'FA:AA';
UPDATE Grants SET recipient_ein = '013' WHERE colocator = 'FA:AA';
UPDATE Grants SET recipient_ein = '014' WHERE colocator = 'FA:AU';
UPDATE Grants SET recipient_ein = '015' WHERE colocator = 'FA:AT';
UPDATE Grants SET recipient_ein = '016' WHERE colocator = 'FA:AZ' OR colocator = 'FA:AJ' OR colocator = 'FA:AJ';
UPDATE Grants SET recipient_ein = '017' WHERE colocator = 'FA:BS' OR colocator = 'FA:BF' OR colocator = 'FA:BF';
UPDATE Grants SET recipient_ein = '018' WHERE colocator = 'FA:BH' OR colocator = 'FA:BA' OR colocator = 'FA:BA';
UPDATE Grants SET recipient_ein = '019' WHERE colocator = 'FA:BD' OR colocator = 'FA:BB' OR colocator = 'FA:BB';
UPDATE Grants SET recipient_ein = '020' WHERE colocator = 'FA:BB';
UPDATE Grants SET recipient_ein = '021' WHERE colocator = 'FA:BY';
UPDATE Grants SET recipient_ein = '022' WHERE colocator = 'FA:BE';
UPDATE Grants SET recipient_ein = '023' WHERE colocator = 'FA:BZ' OR colocator = 'FA:BH' OR colocator = 'FA:BH';
UPDATE Grants SET recipient_ein = '024' WHERE colocator = 'FA:BJ' OR colocator = 'FA:BN' OR colocator = 'FA:BN';
UPDATE Grants SET recipient_ein = '025' WHERE colocator = 'FA:BM';
UPDATE Grants SET recipient_ein = '026' WHERE colocator = 'FA:BT';
UPDATE Grants SET recipient_ein = '027' WHERE colocator = 'FA:BO' OR colocator = 'FA:BL' OR colocator = 'FA:BL';
UPDATE Grants SET recipient_ein = '028' WHERE colocator = 'FA:BA' OR colocator = 'FA:BK' OR colocator = 'FA:BK';
UPDATE Grants SET recipient_ein = '029' WHERE colocator = 'FA:BW' OR colocator = 'FA:BC' OR colocator = 'FA:BC';
UPDATE Grants SET recipient_ein = '030' WHERE colocator = 'FA:BR';
UPDATE Grants SET recipient_ein = '031' WHERE colocator = 'FA:IO' OR colocator = 'FA:IO' OR colocator = 'FA:IO';
UPDATE Grants SET recipient_ein = '032' WHERE colocator = 'FA:VG' OR colocator = 'FA:VI' OR colocator = 'FA:VI';
UPDATE Grants SET recipient_ein = '033' WHERE colocator = 'FA:BN' OR colocator = 'FA:BX' OR colocator = 'FA:BX';
UPDATE Grants SET recipient_ein = '034' WHERE colocator = 'FA:BG' OR colocator = 'FA:BU' OR colocator = 'FA:BU';
UPDATE Grants SET recipient_ein = '034' WHERE colocator = 'FA:BU';
UPDATE Grants SET recipient_ein = '035' WHERE colocator = 'FA:BF' OR colocator = 'FA:UV' OR colocator = 'FA:UV';
UPDATE Grants SET recipient_ein = '036' WHERE colocator = 'FA:BI';
UPDATE Grants SET recipient_ein = '037' WHERE colocator = 'FA:KH' OR colocator = 'FA:CB' OR colocator = 'FA:CB';
UPDATE Grants SET recipient_ein = '038' WHERE colocator = 'FA:CM';
UPDATE Grants SET recipient_ein = '039' WHERE colocator = 'FA:CA';
UPDATE Grants SET recipient_ein = '040' WHERE colocator = 'FA:CV' OR colocator = 'FA:CV' OR colocator = 'FA:CV';
UPDATE Grants SET recipient_ein = '041' WHERE colocator = 'FA:KY' OR colocator = 'FA:CJ' OR colocator = 'FA:CJ';
UPDATE Grants SET recipient_ein = '042' WHERE colocator = 'FA:CF' OR colocator = 'FA:CT' OR colocator = 'FA:CT';
UPDATE Grants SET recipient_ein = '043' WHERE colocator = 'FA:TD' OR colocator = 'FA:CD' OR colocator = 'FA:CD';
UPDATE Grants SET recipient_ein = '044' WHERE colocator = 'FA:CL';
UPDATE Grants SET recipient_ein = '045' WHERE colocator = 'FA:CN' OR colocator = 'FA:CH' OR colocator = 'FA:CH';
UPDATE Grants SET recipient_ein = '046' WHERE colocator = 'FA:CX' OR colocator = 'FA:KT' OR colocator = 'FA:KT';
UPDATE Grants SET recipient_ein = '047' WHERE colocator = 'FA:CC';
UPDATE Grants SET recipient_ein = '048' WHERE colocator = 'FA:CO';
UPDATE Grants SET recipient_ein = '049' WHERE colocator = 'FA:KM' OR colocator = 'FA:CM' OR colocator = 'FA:CM';
UPDATE Grants SET recipient_ein = '050' WHERE colocator = 'FA:CG' OR colocator = 'FA:CF' OR colocator = 'FA:CF';
UPDATE Grants SET recipient_ein = '051' WHERE colocator = 'FA:CD';
UPDATE Grants SET recipient_ein = '052' WHERE colocator = 'FA:CK' OR colocator = 'FA:CN' OR colocator = 'FA:CN';
UPDATE Grants SET recipient_ein = '053' WHERE colocator = 'FA:CR' OR colocator = 'FA:CS' OR colocator = 'FA:CS';
UPDATE Grants SET recipient_ein = '054' WHERE colocator = 'FA:HR' OR colocator = 'FA:HR' OR colocator = 'FA:HR';
UPDATE Grants SET recipient_ein = '055' WHERE colocator = 'FA:CU';
UPDATE Grants SET recipient_ein = '056' WHERE colocator = 'FA:CW';
UPDATE Grants SET recipient_ein = '057' WHERE colocator = 'FA:CY';
UPDATE Grants SET recipient_ein = '058' WHERE colocator = 'FA:CZ' OR colocator = 'FA:EZ' OR colocator = 'FA:EZ';
UPDATE Grants SET recipient_ein = '059' WHERE colocator = 'FA:DK' OR colocator = 'FA:DA' OR colocator = 'FA:DA';
UPDATE Grants SET recipient_ein = '060' WHERE colocator = 'FA:DJ' OR colocator = 'FA:DJ' OR colocator = 'FA:DJ';
UPDATE Grants SET recipient_ein = '061' WHERE colocator = 'FA:DM' OR colocator = 'FA:DO' OR colocator = 'FA:DO';
UPDATE Grants SET recipient_ein = '062' WHERE colocator = 'FA:DO' OR colocator = 'FA:DR' OR colocator = 'FA:DR';
UPDATE Grants SET recipient_ein = '063' WHERE colocator = 'FA:EC' OR colocator = 'FA:EC' OR colocator = 'FA:EC';
UPDATE Grants SET recipient_ein = '064' WHERE colocator = 'FA:EG' OR colocator = 'FA:EG' OR colocator = 'FA:EG';
UPDATE Grants SET recipient_ein = '065' WHERE colocator = 'FA:SV' OR colocator = 'FA:SV' OR colocator = 'FA:SV';
UPDATE Grants SET recipient_ein = '066' WHERE colocator = 'FA:GQ' OR colocator = 'FA:EK' OR colocator = 'FA:EK';
UPDATE Grants SET recipient_ein = '067' WHERE colocator = 'FA:ER' OR colocator = 'FA:ER' OR colocator = 'FA:ER';
UPDATE Grants SET recipient_ein = '068' WHERE colocator = 'FA:EE' OR colocator = 'FA:EN' OR colocator = 'FA:EN';
UPDATE Grants SET recipient_ein = '069' WHERE colocator = 'FA:ET' OR colocator = 'FA:ET' OR colocator = 'FA:ET';
UPDATE Grants SET recipient_ein = '070' WHERE colocator = 'FA:FK';
UPDATE Grants SET recipient_ein = '071' WHERE colocator = 'FA:FO';
UPDATE Grants SET recipient_ein = '072' WHERE colocator = 'FA:FJ' OR colocator = 'FA:FJ' OR colocator = 'FA:FJ';
UPDATE Grants SET recipient_ein = '073' WHERE colocator = 'FA:FI';
UPDATE Grants SET recipient_ein = '074' WHERE colocator = 'FA:FR' OR colocator = 'FA:FR' OR colocator = 'FA:FR';
UPDATE Grants SET recipient_ein = '075' WHERE colocator = 'FA:GF' OR colocator = 'FA:FG' OR colocator = 'FA:FG';
UPDATE Grants SET recipient_ein = '076' WHERE colocator = 'FA:PF' OR colocator = 'FA:FP' OR colocator = 'FA:FP';
UPDATE Grants SET recipient_ein = '077' WHERE colocator = 'FA:TF' OR colocator = 'FA:FS' OR colocator = 'FA:FS';
UPDATE Grants SET recipient_ein = '078' WHERE colocator = 'FA:GA' OR colocator = 'FA:GB' OR colocator = 'FA:GB';
UPDATE Grants SET recipient_ein = '079' WHERE colocator = 'FA:GM' OR colocator = 'FA:GA' OR colocator = 'FA:GA';
UPDATE Grants SET recipient_ein = '080' WHERE colocator = 'FA:GE' OR colocator = 'FA:GG' OR colocator = 'FA:GG';
UPDATE Grants SET recipient_ein = '081' WHERE colocator = 'FA:DE' OR colocator = 'FA:GM' OR colocator = 'FA:GM';
UPDATE Grants SET recipient_ein = '082' WHERE colocator = 'FA:GH' OR colocator = 'FA:GH' OR colocator = 'FA:GH';
UPDATE Grants SET recipient_ein = '083' WHERE colocator = 'FA:GI';
UPDATE Grants SET recipient_ein = '084' WHERE colocator = 'FA:GR' OR colocator = 'FA:GR' OR colocator = 'FA:GR';
UPDATE Grants SET recipient_ein = '085' WHERE colocator = 'FA:GL' OR colocator = 'FA:GL' OR colocator = 'FA:GL';
UPDATE Grants SET recipient_ein = '086' WHERE colocator = 'FA:GD' OR colocator = 'FA:GJ' OR colocator = 'FA:GJ';
UPDATE Grants SET recipient_ein = '087' WHERE colocator = 'FA:GP' OR colocator = 'FA:GP' OR colocator = 'FA:GP';
UPDATE Grants SET recipient_ein = '088' WHERE colocator = 'FA:GU';
UPDATE Grants SET recipient_ein = '089' WHERE colocator = 'FA:GT' OR colocator = 'FA:GT' OR colocator = 'FA:GT';
UPDATE Grants SET recipient_ein = '090' WHERE colocator = 'FA:GG' OR colocator = 'FA:GK' OR colocator = 'FA:GK';
UPDATE Grants SET recipient_ein = '091' WHERE colocator = 'FA:GN' OR colocator = 'FA:GV' OR colocator = 'FA:GV';
UPDATE Grants SET recipient_ein = '092' WHERE colocator = 'FA:GW' OR colocator = 'FA:PU' OR colocator = 'FA:PU';
UPDATE Grants SET recipient_ein = '093' WHERE colocator = 'FA:GY' OR colocator = 'FA:GY' OR colocator = 'FA:GY';
UPDATE Grants SET recipient_ein = '094' WHERE colocator = 'FA:HT' OR colocator = 'FA:HA' OR colocator = 'FA:HA';
UPDATE Grants SET recipient_ein = '095' WHERE colocator = 'FA:HN' OR colocator = 'FA:HO' OR colocator = 'FA:HO';
UPDATE Grants SET recipient_ein = '096' WHERE colocator = 'FA:HK' OR colocator = 'FA:HK' OR colocator = 'FA:HK';
UPDATE Grants SET recipient_ein = '097' WHERE colocator = 'FA:HU' OR colocator = 'FA:HU' OR colocator = 'FA:HU';
UPDATE Grants SET recipient_ein = '098' WHERE colocator = 'FA:IS' OR colocator = 'FA:IC' OR colocator = 'FA:IC';
UPDATE Grants SET recipient_ein = '099' WHERE colocator = 'FA:IN' OR colocator = 'FA:IN' OR colocator = 'FA:IN';
UPDATE Grants SET recipient_ein = '100' WHERE colocator = 'FA:ID';
UPDATE Grants SET recipient_ein = '101' WHERE colocator = 'FA:IR' OR colocator = 'FA:IR' OR colocator = 'FA:IR';
UPDATE Grants SET recipient_ein = '102' WHERE colocator = 'FA:IQ' OR colocator = 'FA:IZ' OR colocator = 'FA:IZ';
UPDATE Grants SET recipient_ein = '103' WHERE colocator = 'FA:IE' OR colocator = 'FA:EI' OR colocator = 'FA:EI';
UPDATE Grants SET recipient_ein = '103' WHERE colocator = 'FA:EI';
UPDATE Grants SET recipient_ein = '104' WHERE colocator = 'FA:IM' OR colocator = 'FA:IM' OR colocator = 'FA:IM';
UPDATE Grants SET recipient_ein = '105' WHERE colocator = 'FA:IL' OR colocator = 'FA:IS' OR colocator = 'FA:IS';
UPDATE Grants SET recipient_ein = '106' WHERE colocator = 'FA:IT';
UPDATE Grants SET recipient_ein = '107' WHERE colocator = 'FA:CI' OR colocator = 'FA:IV' OR colocator = 'FA:IV';
UPDATE Grants SET recipient_ein = '108' WHERE colocator = 'FA:JM' OR colocator = 'FA:JM' OR colocator = 'FA:JM';
UPDATE Grants SET recipient_ein = '109' WHERE colocator = 'FA:JP' OR colocator = 'FA:JA' OR colocator = 'FA:JA';
UPDATE Grants SET recipient_ein = '110' WHERE colocator = 'FA:JE' OR colocator = 'FA:JE' OR colocator = 'FA:JE';
UPDATE Grants SET recipient_ein = '111' WHERE colocator = 'FA:JO' OR colocator = 'FA:JO' OR colocator = 'FA:JO';
UPDATE Grants SET recipient_ein = '112' WHERE colocator = 'FA:KZ' OR colocator = 'FA:KZ' OR colocator = 'FA:KZ';
UPDATE Grants SET recipient_ein = '113' WHERE colocator = 'FA:KE' OR colocator = 'FA:KE' OR colocator = 'FA:KE';
UPDATE Grants SET recipient_ein = '114' WHERE colocator = 'FA:KI' OR colocator = 'FA:KR' OR colocator = 'FA:KR';
UPDATE Grants SET recipient_ein = '115' WHERE colocator = 'FA:KP' OR colocator = 'FA:KN' OR colocator = 'FA:KN';
UPDATE Grants SET recipient_ein = '116' WHERE colocator = 'FA:KR' OR colocator = 'FA:KS' OR colocator = 'FA:KS';
UPDATE Grants SET recipient_ein = '117' WHERE colocator = 'FA:KW' OR colocator = 'FA:KU' OR colocator = 'FA:KU';
UPDATE Grants SET recipient_ein = '118' WHERE colocator = 'FA:KG' OR colocator = 'FA:KG' OR colocator = 'FA:KG';
UPDATE Grants SET recipient_ein = '119' WHERE colocator = 'FA:LA' OR colocator = 'FA:LA' OR colocator = 'FA:LA';
UPDATE Grants SET recipient_ein = '120' WHERE colocator = 'FA:LV' OR colocator = 'FA:LG' OR colocator = 'FA:LG';
UPDATE Grants SET recipient_ein = '121' WHERE colocator = 'FA:LB' OR colocator = 'FA:LE' OR colocator = 'FA:LE';
UPDATE Grants SET recipient_ein = '121' WHERE colocator = 'FA:LE';
UPDATE Grants SET recipient_ein = '122' WHERE colocator = 'FA:LS' OR colocator = 'FA:LS' OR colocator = 'FA:LS';
UPDATE Grants SET recipient_ein = '123' WHERE colocator = 'FA:LR' OR colocator = 'FA:LI' OR colocator = 'FA:LI';
UPDATE Grants SET recipient_ein = '124' WHERE colocator = 'FA:LY' OR colocator = 'FA:LT' OR colocator = 'FA:LT';
UPDATE Grants SET recipient_ein = '125' WHERE colocator = 'FA:LI' OR colocator = 'FA:LY' OR colocator = 'FA:LY';
UPDATE Grants SET recipient_ein = '126' WHERE colocator = 'FA:LT' OR colocator = 'FA:LH' OR colocator = 'FA:LH';
UPDATE Grants SET recipient_ein = '127' WHERE colocator = 'FA:LU' OR colocator = 'FA:LU' OR colocator = 'FA:LU';
UPDATE Grants SET recipient_ein = '128' WHERE colocator = 'FA:MO' OR colocator = 'FA:MN' OR colocator = 'FA:MN';
UPDATE Grants SET recipient_ein = '129' WHERE colocator = 'FA:MK' OR colocator = 'FA:MK' OR colocator = 'FA:MK';
UPDATE Grants SET recipient_ein = '130' WHERE colocator = 'FA:MG' OR colocator = 'FA:MA' OR colocator = 'FA:MA';
UPDATE Grants SET recipient_ein = '131' WHERE colocator = 'FA:MW' OR colocator = 'FA:MI' OR colocator = 'FA:MI';
UPDATE Grants SET recipient_ein = '132' WHERE colocator = 'FA:MY' OR colocator = 'FA:MY' OR colocator = 'FA:MY';
UPDATE Grants SET recipient_ein = '133' WHERE colocator = 'FA:MV' OR colocator = 'FA:MV' OR colocator = 'FA:MV';
UPDATE Grants SET recipient_ein = '134' WHERE colocator = 'FA:ML' OR colocator = 'FA:ML' OR colocator = 'FA:ML';
UPDATE Grants SET recipient_ein = '135' WHERE colocator = 'FA:MT' OR colocator = 'FA:MT' OR colocator = 'FA:MT';
UPDATE Grants SET recipient_ein = '136' WHERE colocator = 'FA:MH' OR colocator = 'FA:RM' OR colocator = 'FA:RM';
UPDATE Grants SET recipient_ein = '137' WHERE colocator = 'FA:MQ' OR colocator = 'FA:MB' OR colocator = 'FA:MB';
UPDATE Grants SET recipient_ein = '138' WHERE colocator = 'FA:MR' OR colocator = 'FA:MR' OR colocator = 'FA:MR';
UPDATE Grants SET recipient_ein = '139' WHERE colocator = 'FA:MU' OR colocator = 'FA:MU' OR colocator = 'FA:MU';
UPDATE Grants SET recipient_ein = '140' WHERE colocator = 'FA:YT' OR colocator = 'FA:MF' OR colocator = 'FA:MF';
UPDATE Grants SET recipient_ein = '141' WHERE colocator = 'FA:MX' OR colocator = 'FA:MX' OR colocator = 'FA:MX';
UPDATE Grants SET recipient_ein = '142' WHERE colocator = 'FA:FM' OR colocator = 'FA:FM' OR colocator = 'FA:FM';
UPDATE Grants SET recipient_ein = '143' WHERE colocator = 'FA:MD' OR colocator = 'FA:MD' OR colocator = 'FA:MD';
UPDATE Grants SET recipient_ein = '144' WHERE colocator = 'FA:MC' OR colocator = 'FA:MC' OR colocator = 'FA:MC';
UPDATE Grants SET recipient_ein = '145' WHERE colocator = 'FA:MN' OR colocator = 'FA:MG' OR colocator = 'FA:MG';
UPDATE Grants SET recipient_ein = '146' WHERE colocator = 'FA:ME' OR colocator = 'FA:MJ' OR colocator = 'FA:MJ';
UPDATE Grants SET recipient_ein = '147' WHERE colocator = 'FA:MS' OR colocator = 'FA:MW' OR colocator = 'FA:MW';
UPDATE Grants SET recipient_ein = '148' WHERE colocator = 'FA:MA' OR colocator = 'FA:MO' OR colocator = 'FA:MO';
UPDATE Grants SET recipient_ein = '149' WHERE colocator = 'FA:MZ' OR colocator = 'FA:MQ' OR colocator = 'FA:MQ';
UPDATE Grants SET recipient_ein = '150' WHERE colocator = 'FA:MM' OR colocator = 'FA:MZ' OR colocator = 'FA:MZ';
UPDATE Grants SET recipient_ein = '151' WHERE colocator = 'FA:NA' OR colocator = 'FA:NA' OR colocator = 'FA:NA';
UPDATE Grants SET recipient_ein = '152' WHERE colocator = 'FA:NR' OR colocator = 'FA:NR' OR colocator = 'FA:NR';
UPDATE Grants SET recipient_ein = '153' WHERE colocator = 'FA:NP' OR colocator = 'FA:NP' OR colocator = 'FA:NP';
UPDATE Grants SET recipient_ein = '154' WHERE colocator = 'FA:NL' OR colocator = 'FA:NL' OR colocator = 'FA:NL';
UPDATE Grants SET recipient_ein = '155' WHERE colocator = 'FA:NC' OR colocator = 'FA:NC' OR colocator = 'FA:NC';
UPDATE Grants SET recipient_ein = '156' WHERE colocator = 'FA:NZ' OR colocator = 'FA:NZ' OR colocator = 'FA:NZ';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:NI' OR colocator = 'FA:NI' OR colocator = 'FA:NI';
UPDATE Grants SET recipient_ein = '158' WHERE colocator = 'FA:NE' OR colocator = 'FA:NE' OR colocator = 'FA:RN' OR colocator = 'FA:NE' OR colocator = 'FA:RN';
UPDATE Grants SET recipient_ein = '159' WHERE colocator = 'FA:NG' OR colocator = 'FA:NG' OR colocator = 'FA:NG';
UPDATE Grants SET recipient_ein = '160' WHERE colocator = 'FA:NU' OR colocator = 'FA:NU' OR colocator = 'FA:NU';
UPDATE Grants SET recipient_ein = '161' WHERE colocator = 'FA:NF' OR colocator = 'FA:NF' OR colocator = 'FA:NF';
UPDATE Grants SET recipient_ein = '162' WHERE colocator = 'FA:MP' OR colocator = 'FA:MP' OR colocator = 'FA:MP';
UPDATE Grants SET recipient_ein = '163' WHERE colocator = 'FA:NO' OR colocator = 'FA:NO' OR colocator = 'FA:NO';
UPDATE Grants SET recipient_ein = '164' WHERE colocator = 'FA:OM';
UPDATE Grants SET recipient_ein = '165' WHERE colocator = 'FA:PK' OR colocator = 'FA:PK' OR colocator = 'FA:PK';
UPDATE Grants SET recipient_ein = '166' WHERE colocator = 'FA:PW';
UPDATE Grants SET recipient_ein = '167' WHERE colocator = 'FA:PS' OR colocator = 'FA:PS' OR colocator = 'FA:PS';
UPDATE Grants SET recipient_ein = '168' WHERE colocator = 'FA:PA' OR colocator = 'FA:PA' OR colocator = 'FA:PA';
UPDATE Grants SET recipient_ein = '169' WHERE colocator = 'FA:PG' OR colocator = 'FA:PP' OR colocator = 'FA:PP';
UPDATE Grants SET recipient_ein = '170' WHERE colocator = 'FA:PY';
UPDATE Grants SET recipient_ein = '171' WHERE colocator = 'FA:PE' OR colocator = 'FA:PE' OR colocator = 'FA:PE';
UPDATE Grants SET recipient_ein = '172' WHERE colocator = 'FA:PH' OR colocator = 'FA:RP' OR colocator = 'FA:RP';
UPDATE Grants SET recipient_ein = '173' WHERE colocator = 'FA:PN' OR colocator = 'FA:PN' OR colocator = 'FA:PN';
UPDATE Grants SET recipient_ein = '174' WHERE colocator = 'FA:PL' OR colocator = 'FA:PL' OR colocator = 'FA:PL';
UPDATE Grants SET recipient_ein = '175' WHERE colocator = 'FA:PT' OR colocator = 'FA:PO' OR colocator = 'FA:PO';
UPDATE Grants SET recipient_ein = '175' WHERE colocator = 'FA:PO';
UPDATE Grants SET recipient_ein = '176' WHERE colocator = 'FA:PR' OR colocator = 'FA:RQ' OR colocator = 'FA:RQ';
UPDATE Grants SET recipient_ein = '176' WHERE colocator = 'FA:RQ';
UPDATE Grants SET recipient_ein = '177' WHERE colocator = 'FA:QA' OR colocator = 'FA:QA' OR colocator = 'FA:QA';
UPDATE Grants SET recipient_ein = '178' WHERE colocator = 'FA:RE' OR colocator = 'FA:RE' OR colocator = 'FA:RE';
UPDATE Grants SET recipient_ein = '179' WHERE colocator = 'FA:RO' OR colocator = 'FA:RO' OR colocator = 'FA:RO';
UPDATE Grants SET recipient_ein = '180' WHERE colocator = 'FA:RU' OR colocator = 'FA:RS' OR colocator = 'FA:RS';
UPDATE Grants SET recipient_ein = '181' WHERE colocator = 'FA:RW' OR colocator = 'FA:RW' OR colocator = 'FA:RW';
UPDATE Grants SET recipient_ein = '182' WHERE colocator = 'FA:BL' OR colocator = 'FA:TB' OR colocator = 'FA:TB';
UPDATE Grants SET recipient_ein = '183' WHERE colocator = 'FA:SH' OR colocator = 'FA:SH' OR colocator = 'FA:SH';
UPDATE Grants SET recipient_ein = '184' WHERE colocator = 'FA:KN';
UPDATE Grants SET recipient_ein = '185' WHERE colocator = 'FA:LC' OR colocator = 'FA:SR' OR colocator = 'FA:SR';
UPDATE Grants SET recipient_ein = '186' WHERE colocator = 'FA:MF';
UPDATE Grants SET recipient_ein = '187' WHERE colocator = 'FA:PM' OR colocator = 'FA:PM' OR colocator = 'FA:SB' OR colocator = 'FA:PM' OR colocator = 'FA:SB';
UPDATE Grants SET recipient_ein = '188' WHERE colocator = 'FA:VC' OR colocator = 'FA:VC' OR colocator = 'FA:VC';
UPDATE Grants SET recipient_ein = '189' WHERE colocator = 'FA:WS' OR colocator = 'FA:WS' OR colocator = 'FA:WS';
UPDATE Grants SET recipient_ein = '190' WHERE colocator = 'FA:SM' OR colocator = 'FA:SM' OR colocator = 'FA:SM';
UPDATE Grants SET recipient_ein = '191' WHERE colocator = 'FA:ST' OR colocator = 'FA:ST' OR colocator = 'FA:ST';
UPDATE Grants SET recipient_ein = '192' WHERE colocator = 'FA:SA' OR colocator = 'FA:SA' OR colocator = 'FA:SA';
UPDATE Grants SET recipient_ein = '193' WHERE colocator = 'FA:SN' OR colocator = 'FA:SN' OR colocator = 'FA:SN';
UPDATE Grants SET recipient_ein = '194' WHERE colocator = 'FA:RS' OR colocator = 'FA:RI' OR colocator = 'FA:RI';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:SC' OR colocator = 'FA:SC' OR colocator = 'FA:SC';
UPDATE Grants SET recipient_ein = '196' WHERE colocator = 'FA:SL' OR colocator = 'FA:SL' OR colocator = 'FA:SL';
UPDATE Grants SET recipient_ein = '197' WHERE colocator = 'FA:SG' OR colocator = 'FA:SG' OR colocator = 'FA:SG';
UPDATE Grants SET recipient_ein = '198' WHERE colocator = 'FA:SX';
UPDATE Grants SET recipient_ein = '199' WHERE colocator = 'FA:SK' OR colocator = 'FA:LO' OR colocator = 'FA:LO';
UPDATE Grants SET recipient_ein = '200' WHERE colocator = 'FA:SI' OR colocator = 'FA:SI' OR colocator = 'FA:SI';
UPDATE Grants SET recipient_ein = '201' WHERE colocator = 'FA:SB' OR colocator = 'FA:BP' OR colocator = 'FA:BP';
UPDATE Grants SET recipient_ein = '202' WHERE colocator = 'FA:SO' OR colocator = 'FA:SO' OR colocator = 'FA:SO';
UPDATE Grants SET recipient_ein = '203' WHERE colocator = 'FA:ZA' OR colocator = 'FA:SF' OR colocator = 'FA:SF';
UPDATE Grants SET recipient_ein = '204' WHERE colocator = 'FA:GS' OR colocator = 'FA:SX' OR colocator = 'FA:SX';
UPDATE Grants SET recipient_ein = '248' WHERE colocator = 'FA:SS';
UPDATE Grants SET recipient_ein = '206' WHERE colocator = 'FA:ES' OR colocator = 'FA:SP' OR colocator = 'FA:SP';
UPDATE Grants SET recipient_ein = '207' WHERE colocator = 'FA:LK' OR colocator = 'FA:CE' OR colocator = 'FA:CE';
UPDATE Grants SET recipient_ein = '208' WHERE colocator = 'FA:SD' OR colocator = 'FA:SU' OR colocator = 'FA:SU';
UPDATE Grants SET recipient_ein = '209' WHERE colocator = 'FA:SR' OR colocator = 'FA:NS' OR colocator = 'FA:NS';
UPDATE Grants SET recipient_ein = '210' WHERE colocator = 'FA:SJ' OR colocator = 'FA:JN' OR colocator = 'FA:JN';
UPDATE Grants SET recipient_ein = '211' WHERE colocator = 'FA:SZ' OR colocator = 'FA:WZ' OR colocator = 'FA:WZ';
UPDATE Grants SET recipient_ein = '212' WHERE colocator = 'FA:SE' OR colocator = 'FA:SW' OR colocator = 'FA:SW';
UPDATE Grants SET recipient_ein = '213' WHERE colocator = 'FA:CH' OR colocator = 'FA:SZ' OR colocator = 'FA:SZ';
UPDATE Grants SET recipient_ein = '214' WHERE colocator = 'FA:SY' OR colocator = 'FA:SY' OR colocator = 'FA:SY';
UPDATE Grants SET recipient_ein = '215' WHERE colocator = 'FA:TW' OR colocator = 'FA:TW' OR colocator = 'FA:TW';
UPDATE Grants SET recipient_ein = '216' WHERE colocator = 'FA:TJ' OR colocator = 'FA:TI' OR colocator = 'FA:TI';
UPDATE Grants SET recipient_ein = '217' WHERE colocator = 'FA:TZ' OR colocator = 'FA:TZ' OR colocator = 'FA:TZ';
UPDATE Grants SET recipient_ein = '218' WHERE colocator = 'FA:TH' OR colocator = 'FA:TH' OR colocator = 'FA:TH';
UPDATE Grants SET recipient_ein = '219' WHERE colocator = 'FA:TL';
UPDATE Grants SET recipient_ein = '220' WHERE colocator = 'FA:TG';
UPDATE Grants SET recipient_ein = '221' WHERE colocator = 'FA:TK' OR colocator = 'FA:TK' OR colocator = 'FA:TK';
UPDATE Grants SET recipient_ein = '222' WHERE colocator = 'FA:TO' OR colocator = 'FA:TO' OR colocator = 'FA:TO';
UPDATE Grants SET recipient_ein = '223' WHERE colocator = 'FA:TT' OR colocator = 'FA:TD' OR colocator = 'FA:TD';
UPDATE Grants SET recipient_ein = '224' WHERE colocator = 'FA:TN' OR colocator = 'FA:TN' OR colocator = 'FA:TN';
UPDATE Grants SET recipient_ein = '225' WHERE colocator = 'FA:TR' OR colocator = 'FA:TU' OR colocator = 'FA:TU';
UPDATE Grants SET recipient_ein = '226' WHERE colocator = 'FA:TM' OR colocator = 'FA:TL' OR colocator = 'FA:TX' OR colocator = 'FA:TL' OR colocator = 'FA:TX';
UPDATE Grants SET recipient_ein = '227' WHERE colocator = 'FA:TC' OR colocator = 'FA:TC' OR colocator = 'FA:TC';
UPDATE Grants SET recipient_ein = '228' WHERE colocator = 'FA:TV' OR colocator = 'FA:TV' OR colocator = 'FA:TV';
UPDATE Grants SET recipient_ein = '229' WHERE colocator = 'FA:UG' OR colocator = 'FA:UG' OR colocator = 'FA:UG';
UPDATE Grants SET recipient_ein = '230' WHERE colocator = 'FA:UA' OR colocator = 'FA:UP' OR colocator = 'FA:UP';
UPDATE Grants SET recipient_ein = '231' WHERE colocator = 'FA:AE' OR colocator = 'FA:TS' OR colocator = 'FA:TS';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:GB' OR colocator = 'FA:UK' OR colocator = 'FA:UK';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:UK';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:EN';
UPDATE Grants SET recipient_ein = '232' WHERE colocator = 'FA:WL';
UPDATE Grants SET recipient_ein = '233' WHERE colocator = 'FA:US' OR colocator = 'FA:US' OR colocator = 'FA:US';
UPDATE Grants SET recipient_ein = '234' WHERE colocator = 'FA:UM';
UPDATE Grants SET recipient_ein = '235' WHERE colocator = 'FA:UY' OR colocator = 'FA:UY' OR colocator = 'FA:UY';
UPDATE Grants SET recipient_ein = '236' WHERE colocator = 'FA:UZ' OR colocator = 'FA:UZ' OR colocator = 'FA:UZ';
UPDATE Grants SET recipient_ein = '237' WHERE colocator = 'FA:VU' OR colocator = 'FA:NH' OR colocator = 'FA:NH';
UPDATE Grants SET recipient_ein = '238' WHERE colocator = 'FA:VE' OR colocator = 'FA:VE' OR colocator = 'FA:VE';
UPDATE Grants SET recipient_ein = '239' WHERE colocator = 'FA:VN' OR colocator = 'FA:VM' OR colocator = 'FA:VM';
UPDATE Grants SET recipient_ein = '240' WHERE colocator = 'FA:VI' OR colocator = 'FA:VQ' OR colocator = 'FA:VQ';
UPDATE Grants SET recipient_ein = '241' WHERE colocator = 'FA:WF' OR colocator = 'FA:WF' OR colocator = 'FA:WF';
UPDATE Grants SET recipient_ein = '242' WHERE colocator = 'FA:EH' OR colocator = 'FA:WA' OR colocator = 'FA:WA';
UPDATE Grants SET recipient_ein = '243' WHERE colocator = 'FA:YE' OR colocator = 'FA:YM' OR colocator = 'FA:YM';
UPDATE Grants SET recipient_ein = '244' WHERE colocator = 'FA:ZM' OR colocator = 'FA:ZA' OR colocator = 'FA:ZA';
UPDATE Grants SET recipient_ein = '245' WHERE colocator = 'FA:ZW' OR colocator = 'FA:ZI' OR colocator = 'FA:ZI';
UPDATE Grants SET recipient_ein = '245' WHERE colocator = 'FA:ZI';
UPDATE Grants SET recipient_ein = '246' WHERE colocator = 'FA:AX';
UPDATE Grants SET recipient_ein = '247' WHERE colocator = 'FA:BQ';
UPDATE Grants SET recipient_ein = '249' WHERE colocator = 'FA:XK';
UPDATE Grants SET recipient_ein = '999' WHERE colocator = 'FA:ZZ';
UPDATE Grants SET recipient_ein = '999' WHERE colocator = 'FA:OC';
UPDATE Grants SET recipient_ein = '999' WHERE colocator = 'FA:PC';