/** Names rolled into the single Patient Subsidies node. Patterns are regexes. */
export default {
  "BIG PHARMA SUBSIDY": {
    "synthetic_ein": "99-7777777",
    "patterns": [
      "AMALGAMATED CHARITABLE",
      "ATTACH(ED|MENT|MENTS)?",
      "AVAILABLE UPON REQUEST",
      "COMPLETE LIST AVAILABLE",
      "CONFIDENTIAL",
      "Contributions gifts grants paid",
      "DETAIL.*(AVAILABLE|UPON)? REQUEST",
      "DETAILED INFORMATION AVAILABLE UPON REQUEST",
      "DETAILED LIST AVAILABLE UPON REQUEST",
      "DRUGS?[ .&]*MEDICINES?",
      "ELIGIBLE[ .]*PATIENTS?",
      "GRANTS APPROVED FOR FUTURE",
      "GRANTS APPROVED PAYABLE",
      "GRANTS PAID DURING",
      "GRANTS PAID FOR",
      "GRANTS PAID TO",
      "GRANTS? (PAID|APPROVED)",
      "HIPAA",
      "HIPPA?",
      "Health Insurance Portability",
      "INFORMATION AVAILABLE",
      "LIST AVAILABLE",
      "LOCAL INITIATIVES SUPPORT",
      "MISC.*",
      "NEEDY[ .]*PATIENTS",
      "Nurses See Schedule",
      "Other - Information Available",
      "Other less than",
      "PATIENT",
      "PATIENTS",
      "PATIENT[ .]*(ASSISTANCE|PROGRAM|PROGRAMS?)",
      "PRIOR YEAR GRANTS PAID",
      "REGULATIONS PREVENT",
      "RELIGIOUS ORGANIZATIONS(SCH",
      "SCH ATTACH",
      "SCHEDULE ATTACH",
      "SEE ATTACHEMENT",
      "SEE[ .]*(ATTACH|SCHEDULE|STATEMENT|LIST|DETAIL)",
      "SEE (DETAIL|LIST)",
      "TOTAL GRANTS PAID",
      "UPON REQUEST",
      "20\\d\\d GRANTS",
      "VARIOUS (501\\(C\\)\\(3\\)|CHARITABLE|GRANTS|NON-PROFIT) ORGANIZATIONS?",
      "VARIOUS GRANTS",
      "VOLUNTEERS",
      "TEACHERS AND STATE EMPLOYEES.*BENEFIT",
      "PART XV IS NOT REQUIRED",
      "DAF - ",
      "FTF QUALITY FIRST SCHOLARSHIPS",
      "CHABOT FAMILY DAF",
      "FEDERAL MINISTRY OF HEALTH AND SOCIAL WELFARE",
      "DONATION OF INVENTORIES",
      "DONATION.*INVENTOR",
      "INVENTOR.*DONATION",
      "RIZ CONSULTING",
      "GO FUND ME",
      "FOUNDATION TO BE NAMED LATER",
      "TO BE NAMED LATER",
      "AVAILABLE ON REQUEST",
      "CYBERGRANTS SPV",
      "93108 FUND",
      "CHILDCARE PAYMENTS",
      "GOODPIX LLC",
      "GURLAND DOCUMENTARIES",
      "AMERICAN CANER SOCIETY",
      "SEE EXHIBIT",
      "UVU FOUNDATION",
      "SFCC FOUNDATION",
      "ECTC FOUNDATION",
      "JCTC FOUNDATION",
      "CEW FOUNDATION",
      "NATIONAL KERATOCONUS FOUNDATION",
      "FERST FOUNDATION",
      "KD FOUNDATION",
      "GU OAUR LOCKBOX",
      "KUPAS HADAYANIM",
      "MAZKERET HALFON",
      "MECHON MASEH ROKEACH",
      "TOVA UVRACHA",
      "(?<!C)ATCH",
      "HIPA",
      "FCPA",
      "\\bSUBGRANT\\b",
      "\\bFILING\\b",
      "\\bSUMMARY\\b",
      "\\bSCHEDULE\\b",
      "PARTNERS IN LEAR",
      "PHILANTHROPH",
      "Numerous Individuals",
      "meet .* Requirements",
      "PAP Requirements",
      "Individuals that meet",
      "SEE ATTACHMENT A",
      "ATTACHMENT A",
      "STATEMENT( [0-9A-Z]+)?",
      "TOTAL",
      "FULL SCHEDULE KEPT ON FILE",
      "SCHEDULE KEPT ON FILE",
      "KEPT ON FILE",
      "CONTRACT PHARMACAL",
      "PHARMACAL CORP",
      "PUBLIC LIBRAR(IES|Y)",
      "UNITED NATIONS",
      "FOOD AND AGRICULTURE ORGANIZATION OF THE UNITED NATIONS",
      "SUBRECIPIENTS",
      "\\bPASS.?THROUGH\\b",
      "\\bAGENCY.?DISTRIB",
      "\\bREIMBURSE",
      "\\bCACFP",
      "\\bFBO\\b",
      "VPK",
      "\\bDISTRIBUTIONS?\\b",
      "FOOD REIMBURS",
      "PASS THROUGH PMTS",
      "FBO",
      "\\(FBO",
      "FOR THE BENEFIT OF",
      "SUB RECIPIENT",
      "PAYMENT TO",
      "DISTRIBUTION TO",
      "REIMBURSEMENT",
      "135 AGENCY",
      "AGENCY DISTRIBUTION",
      "PASS THRU",
      "THRU PMTS"
    ]
  },
};
