/** Copied from 990tools/big_pharma_subsidy.json — edit the JSON, then recopy. */
export default {
  "BIG PHARMA SUBSIDY": {
    "synthetic_ein": "99-7777777",
    "description": "Rollup for all subsidy/aggregate/privacy rows (SEE ATTACHED, VARIOUS, HIPPA, PATIENT, Drugs & Medicines, etc.). Synthetic EIN for grant visualization and fraud detection. Patterns are treated as regex in the generator and as substring in extractor/TUI. 20260603: +11 from 100M part01 + bmf stats; +~25 more from hard analysis. 20260604: + pass-through/flow (PASS THROUGH, AGENCY DISTRIB, REIMBURSE, FBO, CACFP, VPK, DISTRIBUTIONS, FOOD REIMBURS, and more FBO/(FBO/FOR THE BENEFIT/SUB RECIPIENT etc.) per user observation that many remaining after phonebook are intermediary/forwarded/subgrant flows or accounting lines rather than direct BMF org recipients (NGO A passes to B, or listed name is the flow desc). User review (post 89% cream): 'we're done with this mapping project. 89% from 34% is huge... Just need to finish the hygiene, then think about how we want to tie this off in a bow' (options: A move einless to subfolder 990tools/einless/{data,docs,code}; B leave as-is; C integrate as step in irs990processor.py). Next: integrate results with address_matcher.py + grant_matcher.py (leverage pre-phonebook generate_name_rules.py canonical rollup heuristics + secondary geo pass). Trusts big_pharma rules over is_org keep logic for hard sus per user. Real common foundations that match BMF still need to pass trad layers to not be hard.",
    "patterns": [
      "AMALGAMATED CHARITABLE",
      "ATTACH(ED|MENT|MENTS)?",
      "AVAILABLE UPON REQUEST",
      "COMPLETE LIST AVAILABLE",
      "CONFIDENTIAL",
      "Contributions gifts grants paid",
      "DETAIL.*(AVAILABLE|UPON)? REQUEST",
      "DETAILED INFORMATION AVAILABLE UPON REQUEST",
      "DETAILED LIST AVAILABLE UPON REQUEST",
      "DRUGS?[ .&]*MEDICINES?",
      "ELIGIBLE[ .]*PATIENTS?",
      "GRANTS APPROVED FOR FUTURE",
      "GRANTS APPROVED PAYABLE",
      "GRANTS PAID DURING",
      "GRANTS PAID FOR",
      "GRANTS PAID TO",
      "GRANTS? (PAID|APPROVED)",
      "HIPAA",
      "HIPPA?",
      "Health Insurance Portability",
      "INFORMATION AVAILABLE",
      "LIST AVAILABLE",
      "LOCAL INITIATIVES SUPPORT",
      "MISC.*",
      "NEEDY[ .]*PATIENTS",
      "Nurses See Schedule",
      "Other - Information Available",
      "Other less than",
      "PATIENT",
      "PATIENTS",
      "PATIENT[ .]*(ASSISTANCE|PROGRAM|PROGRAMS?)",
      "PRIOR YEAR GRANTS PAID",
      "REGULATIONS PREVENT",
      "RELIGIOUS ORGANIZATIONS(SCH",
      "SCH ATTACH",
      "SCHEDULE ATTACH",
      "SEE ATTACHEMENT",
      "SEE[ .]*(ATTACH|SCHEDULE|STATEMENT|LIST|DETAIL)",
      "SEE (DETAIL|LIST)",
      "TOTAL GRANTS PAID",
      "UPON REQUEST",
      "20\\d\\d GRANTS",
      "VARIOUS (501\\(C\\)\\(3\\)|CHARITABLE|GRANTS|NON-PROFIT) ORGANIZATIONS?",
      "VARIOUS GRANTS",
      "VOLUNTEERS",
      "TEACHERS AND STATE EMPLOYEES.*BENEFIT",
      "PART XV IS NOT REQUIRED",
      "DAF - ",
      "FTF QUALITY FIRST SCHOLARSHIPS",
      "CHABOT FAMILY DAF",
      "FEDERAL MINISTRY OF HEALTH AND SOCIAL WELFARE",
      "DONATION OF INVENTORIES",
      "DONATION.*INVENTOR",
      "INVENTOR.*DONATION",
      "RIZ CONSULTING",
      "GO FUND ME",
      "FOUNDATION TO BE NAMED LATER",
      "TO BE NAMED LATER",
      "AVAILABLE ON REQUEST",
      "CYBERGRANTS SPV",
      "93108 FUND",
      "CHILDCARE PAYMENTS",
      "GOODPIX LLC",
      "GURLAND DOCUMENTARIES",
      "AMERICAN CANER SOCIETY",
      "SEE EXHIBIT",
      "UVU FOUNDATION",
      "SFCC FOUNDATION",
      "ECTC FOUNDATION",
      "JCTC FOUNDATION",
      "CEW FOUNDATION",
      "NATIONAL KERATOCONUS FOUNDATION",
      "FERST FOUNDATION",
      "KD FOUNDATION",
      "GU OAUR LOCKBOX",
      "KUPAS HADAYANIM",
      "MAZKERET HALFON",
      "MECHON MASEH ROKEACH",
      "TOVA UVRACHA",
      "(?<!C)ATCH",
      "HIPA",
      "FCPA",
      "\\bSUBGRANT\\b",
      "\\bFILING\\b",
      "\\bSUMMARY\\b",
      "\\bSCHEDULE\\b",
      "PARTNERS IN LEAR",
      "PHILANTHROPH",
      "Numerous Individuals",
      "meet .* Requirements",
      "PAP Requirements",
      "Individuals that meet",
      "SEE ATTACHMENT A",
      "ATTACHMENT A",
      "STATEMENT( [0-9A-Z]+)?",
      "TOTAL",
      "FULL SCHEDULE KEPT ON FILE",
      "SCHEDULE KEPT ON FILE",
      "KEPT ON FILE",
      "CONTRACT PHARMACAL",
      "PHARMACAL CORP",
      "PUBLIC LIBRAR(IES|Y)",
      "UNITED NATIONS",
      "FOOD AND AGRICULTURE ORGANIZATION OF THE UNITED NATIONS",
      "SUBRECIPIENTS",
      "\\bPASS.?THROUGH\\b",
      "\\bAGENCY.?DISTRIB",
      "\\bREIMBURSE",
      "\\bCACFP",
      "\\bFBO\\b",
      "VPK",
      "\\bDISTRIBUTIONS?\\b",
      "FOOD REIMBURS",
      "PASS THROUGH PMTS",
      "FBO",
      "\\(FBO",
      "FOR THE BENEFIT OF",
      "SUB RECIPIENT",
      "PAYMENT TO",
      "DISTRIBUTION TO",
      "REIMBURSEMENT",
      "135 AGENCY",
      "AGENCY DISTRIBUTION",
      "PASS THRU",
      "THRU PMTS"
    ]
  }
};
